folio-org/platform-core

test/ui-testing/100-startpage.js
test/ui-testing/110-auth-success.js
test/ui-testing/120-auth-fail.js
test/ui-testing/calendarTest.js
test/ui-testing/codex-search.js
test/ui-testing/dependencies.js
test/ui-testing/exercise.js
test/ui-testing/inventorySearch.js
test/ui-testing/loan_renewal.js
test/ui-testing/location.js
test/ui-testing/profile-pictures.js
test/ui-testing/stub.js
test/ui-testing/vendor.js

Move tests from ui-testing into platform-core

UITEST-22 move tests

---

.eslintrc
CHANGELOG.md
README.md
package.json
stripes.config.js
test/.eslintrc
test/ui-testing/100-startpage.js
test/ui-testing/110-auth-success.js
test/ui-testing/120-auth-fail.js
test/ui-testing/calendarTest.js
test/ui-testing/codex-search.js
test/ui-testing/dependencies.js
test/ui-testing/exercise.js
test/ui-testing/inventorySearch.js
test/ui-testing/loan_renewal.js
test/ui-testing/location.js
test/ui-testing/profile-pictures.js
test/ui-testing/stub.js
test/ui-testing/test.js
test/ui-testing/vendor.js

With this PR, the platform tests can be run from within platform-core, using `yarn test`. This requires that platform-core has been built and is running somewhere (`--url` may be provided).  See the README for more information.
Additional work:
* Verify tests run as expected in CI
* Fix remaining lint errors.  I corrected several basic ones here, but did not want to muddy the PR with further changes.
* Remove arrow functions from Mocha tests. The bound `this` will interfere with the Mocha context. See https://mochajs.org/#arrow-functions
* Include a Jenkinsfile
* Move tests for calendar and vendor apps once an appropriate platform is available
* Integrate with Stripes-CLI

UITEST-22 pass test context to tests

---

test/ui-testing/new_proxy.js

Module integration tests don't belong in the module because running them
prevents the module from being tested in isolation.
Refs [UIU-605](https://issues.folio.org/browse/UIU-605)

move ui-users integration tests here

---

renovate.json

reconfigure renovate

---

package.json
test/ui-testing/100-startpage.js
test/ui-testing/110-auth-success.js
test/ui-testing/codex-search.js
test/ui-testing/inventorySearch.js
yarn.lock

Replaces https://github.com/folio-org/platform-core/pull/89

Update eslint-config-stripes to 3.2.1

---

test/ui-testing/codex-search.js

The `title` attribute is being phased out so we need to rewrite tests to
watch for other attributes.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)

test without the `title` attribute

---

test/ui-testing/exercise.js
test/ui-testing/loan_renewal.js
test/ui-testing/new_proxy.js

The `title` attribute is being phased out so we need to hang tests off
other attributes.
Additionally, it appears that `xclick` may be dangerous to your health,
or at least needs to be used with caution. In Nightmare, some functions,
like `evaluate()` return promises and therefore _must_ be followed by a
`then(nightmare ... done()).catch()` call that contains the remainder of
the test. Without a `then()`, you can find yourself in a dangling
process that will eventually timeout.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)

don't hang tests off `title` attribute

---

test/ui-testing/exercise.js

On checkout, it is _sometimes_ the case that if you click the 'Enter'
button very quickly after entering a value in the patron-id field you
get the error message, "User with this id does not exist". I can
sometimes get this in manual testing by typing a username and
immediately hitting the enter key.
Refs [UICHKOUT-473](https://issues.folio.org/browse/UICHKOUT-473)

wait after username entry on checkout

---

package.json
test/ui-testing/100-startpage.js
test/ui-testing/110-auth-success.js
test/ui-testing/120-auth-fail.js
test/ui-testing/calendarTest.js
test/ui-testing/codex-search.js
test/ui-testing/dependencies.js
test/ui-testing/exercise.js
test/ui-testing/inventorySearch.js
test/ui-testing/loan_renewal.js
test/ui-testing/location.js
test/ui-testing/new_proxy.js
test/ui-testing/profile-pictures.js
test/ui-testing/stub.js
test/ui-testing/test.js
test/ui-testing/vendor.js

Added nightmare modifications to tests.  Added package.json updates to include modules that are in the platform

Platform coverage enable

---

package.json
test/ui-testing/codex-search.js
test/ui-testing/exercise.js
test/ui-testing/loan_renewal.js
test/ui-testing/new_proxy.js

* update ui-inventory to v1.5.2 and ui-users to v2.19.0.
* pull integration test updates from the `snapshot` branch so they are more stable and reflect recent changes to the apps they interact with.
Refs [FOLIO-1665](https://issues.folio.org/browse/FOLIO-1665)

Include app updates

---

package.json
test/ui-testing/loan_renewal.js

UICIRC-121: Fix nightmare tests for "loan_renewal" scenario for https://github.com/folio-org/ui-circulation/pull/141

UICIRC-121

---

test/ui-testing/loan_renewal.js

The save-button selector for loan policies incorrectly referenced fixed
due date schedules. I'm not sure how that ever worked.

fix loan policy save selector

---

test/ui-testing/loan-renewal.js

https://github.com/folio-org/mod-circulation/pull/184

UIU-724: Change error messages according to backend changes.

---

test/ui-testing/loan-renewal.js

Aw geez yet another "I'm not sure how this ever worked before" commit.
Previously, we saved the default loan rules to a variable defined in
Nightmare from the context of the browser. That ain't right. So now, we
correctly save the rules in the context of nightmare so that we can
restore them when the test finishes.
Coupled with folio-org/ui-circulation/pull/268, this should allow the
loan-renewal test to pass.
Refs [STRIPES-602](https://issues.folio.org/browse/STRIPES-602)

correctly restore loan rules

---

test/ui-testing/new-request.js

The pickup service point has been made mandatory to be selected while creating a request as a part of UIREQ-227. Hence, we need to incorporate this logic into the tests. This PR does it.

Select pickup service point while creating a request

---

test/ui-testing/loan-renewal.js

Initialize all policies, including notice-policies and request-policies,
before using them in circulation rules. Previously, the applied
circulation rules assumed the existance of policies which may not have
been present.

init all policies for rules

---

install.json
okapi-install.json
test/ui-testing/loan-renewal.js
yarn.lock

Click things in Nightmare's scope instead of the browser's scope.
Clicking in browserland sends Nightmare into Neverneverland. This brings
the loan policy handler into line with how the others are written and
should be more reliable.

avoid browser-scoped clicks

---

renovate.json

Reconfigure Renovate 

---

test/ui-testing/loan-renewal.js

On many pages, the delete action has moved from a single button to an
entry on the dropdown carat menu so the tests now accommodate that.
Action confirmations are now a bit more robust, relying on the
appearance and wording of the message in the confirmation-toast message.
Data cleanup is better; there are no dangling notice or request
policies.
Refs [UICIRC-237](https://issues.folio.org/browse/UICIRC-237)

adjust delete; more robust confirmations

---

test/ui-testing/loan-renewal.js

A test looked for a particular message which was out of sync with the most recent translations.

use new translation value in test

---

README.md
yarn.lock

And a test PR for FOLIO-1963 doc.

FOLIO-1021 Update copyright year

---

test/ui-testing/new-proxy.js

Change ids according to https://github.com/folio-org/ui-users/pull/822

UIU-981: Fix tests.

---

CHANGELOG.md
package.json
test/ui-testing/codex-search.js
test/ui-testing/dependencies.js
test/ui-testing/exercise.js
test/ui-testing/loan-renewal.js
test/ui-testing/new-proxy.js
test/ui-testing/new-request.js
yarn.lock

Apps are guaranteed to show up in the app-menu but not on the navigation
bar, so tests need to navigate by clicking menu items.

navigate via the app-menu instead of icons

---

package.json

The renamed ui-tenant-settings was already added in recent merges.

FOLIO-2018 Remove remnant ui-organization

---

package.json
test/ui-testing/loan-renewal.js
test/ui-testing/new-request.js

Common functions `checkout` and `setCirculationRules` do a good job of
making sure an action is fully complete rather than just clicking the
button that starts the action, i.e. they wait for some sort of success
condition. This seems particularly important in the case of checkout.

use stripes-testing for checkout and circ-settings

---

test/ui-testing/loan-renewal.js
test/ui-testing/new-request.js

So much has changed, and yet so much is the same. `setCirculationRules`
is now much more reliable.

update integration tests

---

package.json
test/ui-testing/new-request.js

Update integration test selectors to (a) be more semantic and less
syntax-dependent and (b) reflect the updated markup of the MCL.
Refs [STCOM-363](https://issues.folio.org/browse/STCOM-363)

STCOM-363 update integration test selectors

---

test/ui-testing/exercise.js
test/ui-testing/loan-renewal.js

Update user-related integration tests now that The Great Routing
Refactor has been merged.
Refs [UIU-897](https://issues.folio.org/browse/UIU-897) / folio-org/ui-users/pull/839

UIU-897 update integration tests

---

test/ui-testing/new-proxy.js

Refactor this for increased reliability. Note especially changes to
handling of submit buttons per folio-org/ui-users/pull/1021.

update new-proxy test

---

test/ui-testing/many-items.js
test/ui-testing/test.js

New test creates >10 items under a single instance record and checks
them all out to a single user in order to test that reports include
limit clauses in their queries in order to retrieve more than the
default number (10) of records.

test with more than 10 items checked out

---

test/ui-testing/loan-renewal.js

Fix broken id for loan-renewal scenario.

UICIRC-372 - Fix broken test

---

test/ui-testing/loan-renewal.js

Change id for request policy save button in order to fix loan-renewal test scenario,

UICIRC-369 - Create/Edit Request policies | Move Save/Cancel buttons to the footer

---

test/ui-testing/many-items.js

Not sure how I missed this earlier. What a bonehead.

use variable, not a constant, for counting

---

test/ui-testing/loan-renewal.js

PR #452 corrected the submit-button selectors for create-loan-policy
tests here but missed it for the change-loan-policy tests.
Refs [UICIRC-372](https://issues.folio.org/browse/UICIRC-372)

UICIRC-372 correct selector for all loan-policy changes

---

Jenkinsfile
test/ui-testing/codex-search.js
test/ui-testing/exercise.js
test/ui-testing/loan-renewal.js
test/ui-testing/many-items.js
test/ui-testing/new-proxy.js
test/ui-testing/new-request.js
test/ui-testing/test.js
yarn.lock

Most of these updates relate to changes in required fields in
circulations rules and form buttons that have moved from the top of a
form to a fixed-footer.
Refs [UITEST-72](https://issues.folio.org/browse/UITEST-72)

UITEST-72 update nightmare tests with 2019-Q4 changes

---

test/ui-testing/new-request.js

Change save button id for requests form.
https://issues.folio.org/browse/UIREQ-370
https://github.com/folio-org/ui-requests/pull/468

UIREQ-370 - Create/Edit a request | Move Save/Cancel buttons to the footer

---

test/ui-testing/exercise.js

Use helpers to add/remove overdue fine policy, lost item fee policy, and
patron notice policy in the circulation rules that are created. Checkout
is now smart enough to check all the attributes of circulation policies
and if we just use dummy values, checkout will fail.

FOLIO-2440 temp policies in exercise test

---

test/ui-testing/new-proxy.js

Why was I faffing about with policies and circulation rules in the
new-proxy test? TBH, I have no idea.

FOLIO-2440 remove superfluous new-proxy helpers

---

test/ui-testing/new-request.js

Remove a wait clause that was inadvertently committed.

FOLIO-2440 remove extra wait clause

---

install.json
package.json
stripes-install.json
test/ui-testing/new-request.js
yarn.lock

The save-button `id` attribute changed.
Refs [UIREQ-370](https://issues.folio.org/browse/UIREQ-370)

UIREQ-370 update button id

---

test/ui-testing/exercise.js
yarn.lock

This test fails in CI. I don't know why; it doesn't fail when I run it
locally against the instances created in CI. Here are a few small things
to maybe slow it down a bit and have a better chance of passing
reliably.

make the exercise test more patient

---

Jenkinsfile
install.json
okapi-install.json
yarn.lock

- Update Jenkinsfile to use K8s on release branch. 
- Update mod-inventory to 14.0.1

Use K8s for PR builds

---

package.json

stripes 4
react-intl 4.5.3
moment 2.25.3

STRIPES-672 stripes 4

---

test/ui-testing/auth-fail.js

The wrapper classes for authentication errors changed under the auspices
of STCOR-430 / /folio-org/stripes-core/pull/875
Refs [STCOR-430](https://issues.folio.org/browse/STCOR-430)

STCOR-430 test updates

---

test/ui-testing/new-proxy.js

As in #601, deal with changes to MCL internals pursuant to UICHKOUT-602
/ /folio-org/stripes-components/pull/1205.
Refs [UICHKOUT-602](https://issues.folio.org/browse/UICHKOUT-602)

UICHKOUT-602 proxy test updates

---

test/ui-testing/loan-renewal.js

Move fixed-due-date-schedule handling out to a helper function imported
from stripes-testing since that's where all the other circ-related
handlers live.
Refs [FOLIO-2727](https://issues.folio.org/browse/FOLIO-2727)

FOLIO-2727 test tweaks

---

CHANGELOG.md
package.json

[STRIPES-694](https://issues.folio.org/browse/STRIPES-694)

STRIPES-694 update react-intl to v5

---

Jenkinsfile
install-extras.json
install.json
okapi-install.json
stripes-install.json
yarn.lock

Fix edge q2 2020

---

CHANGELOG.md
package.json

Refs [STRIPES-702](https://issues.folio.org/browse/STRIPES-702)

STRIPES-702 upgrade moment to v2.29

---

package.json
test/ui-testing/auth-fail.js
test/ui-testing/auth-success.js
test/ui-testing/calendar.js
test/ui-testing/codex-search.js
test/ui-testing/dependencies.js
test/ui-testing/exercise.js
test/ui-testing/find-active.js
test/ui-testing/loan-renewal.js
test/ui-testing/many-items.js
test/ui-testing/many-requests.js
test/ui-testing/new-proxy.js
test/ui-testing/new-request.js
test/ui-testing/profile-pictures.js
test/ui-testing/start-page.js
test/ui-testing/stub.js
test/ui-testing/test.js
test/ui-testing/vendor.js

Reverts folio-org/platform-core#793
The [platform-complete build failed](https://jenkins-aws.indexdata.com/job/FOLIO_Reference_Builds/job/folio-snapshot/781/) after this PR was merged in a way that I didn't expect. I'm not convinced it's related, but neither that it's unrelated, so for now I'm reverting this change.

Revert "UITEST-77 remove NightmareJS tests"

---

stripes.config.js
yarn.lock

Should fix UIIN-1474, the using new facility added in UIIN-1480.

In stripes.config.js set maxUnpagedResourceCount to 2000

---

package.json

[STRIPES-722](https://issues.folio.org/browse/STRIPES-722)

STRIPES-722 bump react to v17
