folio-org/platform-core

- CHANGELOG.md
- README.md
- package.json
This allows platform and app tests to be run together in the same call to ui-testing's test-module.  Examples in the README have been updated to reflect this.
See UITEST-36 for details.
> Update package scripts to support working directory token

- test/ui-testing/new_proxy.js
Nine wouldn't display with a filter
Nine wouldn't display with a search
And the "active" checkbox is no longer
Though UIU-400 I should not besmirch
Seven, eight, nine!
Help the tester find the line!
It was an itsy bisty teenie weenie list of only fo-ur users
That you got when searched for '0'
It was an itsy bitsy teenie weenie list without a ni-inth user
The test waited. Forever. No joke.
> don't wait for non-existent rows to appear

- test/ui-testing/exercise.js
The checkout action in exercise.js would sometimes register as failed
even though it was clear the checkout action itself succeeded (because
subsequent actions relying on an item being checked out were
successful). This meant the test itself, rather than the behavior it was
supposed to be testing, was at fault.
Fixes [UITEST-54](https://issues.folio.org/browse/UITEST-54)
> remove exercise.js test timers

- package.json
This updates the snapshot branch for stripes framework v1.  Rather than use >=0.0.0, I've applied the minimum versions of dependencies required to be compatible with stripes-framework v1, such as:
```
"@folio/users": ">=2.17.0",
```
Stripes framework uses the caret syntax to help guard against any future breaking changes leaking into the snapshot branch before they are ready for use in a platform.
```
"@folio/stripes": "^1.0.0",
```
> Update snapshot for stripes framework v1

- test/ui-testing/loan_renewal.js
Two sets of changes here: had to update a bunch of `id` attributes that
changed to be more consistent, and avoid use of `xtract` and clicking
elements within `evaluate()` calls as they seem to explode when they
fail and leave Electron instances hanging out all over the place,
leading later tests to fail mysteriously, which is super fun to debug.
> make loan-renewal tests more reliable

- test/ui-testing/codex-search.js
Simplify the code to evaluate the success of the filters, and accommodate the fact that the codex will likely return many records for any given search now that we have eholdings enabled.
> simplify codex tests

- test/ui-testing/loan_renewal.js
I don't know what it is about deleting items from `<ControlledVocab>`
that makes Nightmare so cranky, but it gets hungup somehow after an
entry is removed and sits there, preventing navigation away from the
page. See also folio-org/ui-organization/pull/165 for a similar problem
and similar fix and similar comment.
> add timeout to handle CV deletion

- test/ui-testing/loan_renewal.js
The loan renewal tests were failing due to a wrongly passed id into FormattedMessage.
Also, the fdds creation was failing due to a date formatting issue where datepicker was not considering the locale format (MM/DD/YYYY) to be valid and had to be passed in as 'YYYY-MM-DD'
> fix the failing loan renewal tests

- test/ui-testing/new_proxy.js
barcodes are likely to be unique across the system, but usernames (or
portions thereof) may turn up in other users' names. Because the
user-search feature includes username, first name, last name, and email,
this means that while the username itself may be unique, a search for it
may turn up multiple rows.
Fixes [FOLIO-1657](https://issues.folio.org/browse/FOLIO-1657)
> store proxy's barcode, not username

- test/ui-testing/120-auth-fail.js
- test/ui-testing/codex-search.js
- test/ui-testing/dependencies.js
- test/ui-testing/exercise.js
- test/ui-testing/loan_renewal.js
- test/ui-testing/new_proxy.js
Using the passed-in instance of Nightmare leads to weird, weird results
where tests seem to run interleaved with one another and things
generally fall apart in strange, unpredictable ways that ultimately
result in tests that fail when run as part of a suite but succeed when
run individually.
It's like the instance of Nightmare gets tired and just can't keep
itself together. Sadly, this means we can't use Nightmare to collect
coverage data since it's using that single instance that allows us to
generate that data. Alas.
Fixes [FOLIO-1660](https://issues.folio.org/browse/FOLIO-1660)
> instantiate new Nightmare instance for tests

- test/ui-testing/120-auth-fail.js
`end()` is required to terminate the Nightmare instance.
Fixes [FOLIO-1662](https://issues.folio.org/browse/FOLIO-1662)
> restore end

- test/ui-testing/codex-search.js
The EBSCO Knowledge Base may or may not be configured, which means
filters may have different effects depending on if and how many results
are returned by the EKB. This update attempts to test filtering with
filters that are not used by the EKB, hence immune to its presence or
absence.
> use filters unaffected by EKB configuration

- package.json
Per the stripes documentation, the platform must declare the
dependencies that other packages depend on.
See https://github.com/folio-org/stripes/blob/master/doc/stripes-framework.md#upgrading-to-v11
> include required dependencies in platform

- package.json
Related to #138.  However with this being snapshot, I used `^` versions rather than `~` since we were already doing that with `stripes` itself.
> Add third-party dependencies per Stripes v1.1 recommendation

- package.json
Update releases of ui-checkout and ui-requests to enforce the
patron-blocks feature that was implemented in ui-users v2.19.0. Creating
blocks is only useful if they're actually enforced.
> enforce patron blocks

- package.json
Resolves these warnings introduced in https://github.com/folio-org/platform-core/pull/151:
```
warning package.json: "dependencies" has dependency "react" with range "^16.6.3" that collides with a dependency in "devDependencies" of the same name with version "~16.6.0"
warning package.json: "dependencies" has dependency "react-dom" with range "^16.6.3" that collides with a dependency in "devDependencies" of the same name with version "~16.6.0"
warning package.json: "dependencies" has dependency "react-redux" with range "^5.1.1" that collides with a dependency in "devDependencies" of the same name withversion "~5.1.1"
warning package.json: "dependencies" has dependency "redux" with range "^3.7.2" that collides with a dependency in "devDependencies" of the same name with version "~3.7.2"
```
> Remove duplicate devDependencies

- CHANGELOG.md
- package.json
This branch already has been upgraded to stripes 2.0.0.  This PR bumps the version to have something to tag/release and later include in platform-complete snapshot.
> Release v1.3.0 snapshot

- test/ui-testing/loan_renewal.js
Save users' barcodes instead of their usernames; it's much more likely to be a unique match when we're attempting to retrieve the same user later in the test and we can do so simply because the search only generates one result.
> find users by barcode, not username

- test/ui-testing/loan_renewal.js
the save-button selector for loan policies incorrectly referenced fixed
due date schedules. I'm not sure how that ever worked.
> fix loan policy save button selector

- test/ui-testing/new-request.js
- test/ui-testing/test.js
new-request relies on users, inventory, checkout, and requests. Tests
integrating multiple apps belong on the platform, not on individual
apps. Moved from ui-requests.
Refs [UIREQ-216](https://issues.folio.org/browse/UIREQ-216)
> move request integration tests to platform

- test/ui-testing/exercise.js
Navigating to a different app immediately after creating an item
record frequently fails, so now we wait a little.
Refs [STRIPES-602](https://issues.folio.org/browse/STRIPES-602)
> wait just a little bit longer

- test/ui-testing/new-request.js
Fields in the request form were recently rearranged such that it is now
necessary to choose an item before setting the request type. The test
test did not reflect this new order, but now it does.
Refs [STRIPES-602](https://issues.folio.org/browse/STRIPES-602), [UIREQ-208](https://issues.folio.org/browse/UIREQ-208)
> complete request form in order

- test/ui-testing/exercise.js
A CSS class used by the exercise test was recently deprecated in
folio-org/stripes-components/pull/866. The exercise test happened to
rely on that class so it needed to be updated.
Fixes [STRIPES-604](https://issues.folio.org/browse/STRIPES-604)
> bring css selector up to date

- test/ui-testing/dependencies.js
- test/ui-testing/profile-pictures.js
The `clickable-settings` button may not always be available in the UI.
Specifically if there are more than 11 apps in the bundle, then it will
not be available. But there's still hope! The element in the apps menu
_is_ always available, and this change updates tests to find that
element instead.
Refs [STRIPES-606](https://issues.folio.org/browse/STRIPES-606)
> use always-available settings identifier

- test/ui-testing/exercise.js
- test/ui-testing/new-request.js
Apply default loan rules before tests begin and restore the existing
rules when tests end. This insulates checkout operations here from
changes (and errors during those changes) to loan rules made by other
tests.
> apply default rules before tests

- test/ui-testing/loan-renewal.js
avoid clicking links in browser scope. instead, try even harder to
figure out a CSS selector for the thing to be clicked and pass that back
to Nightmare and let Nightmare click it. That seems to make Nightmare
happy, and does a better job of avoiding the problem of Nightmare
getting lost in the never neverland of parallel execution.
Of course, this isn't completely true as the 'renew loan' checkboxes
are, strangely, unclickable in Nightmare's scope. WTF?
> don't click on things in browser scope

- Jenkinsfile
- package.json
- test/ui-testing/loan-renewal.js
`<DatePicker>` now supports locale-formatted dates. You get these
automatically when using the UI to select a date, but when pasting a
string into the field it must be correctly formatted to match the
locale.
Release v1.6.1 of ui-circulation incorporates the `<DatePicker>` changes
which are reflected in the updated test here that sets a specific locale
and then uses dates formatted for that locale.
> use locale-formatted dates

- package.json
Provide a current release of React, v16.8, the one with hooks.
Refs [STRIPES-599](https://issues.folio.org/browse/STRIPES-599)
> provide react 16.8, the one with hooks

- test/ui-testing/loan-renewal.js
* set the loan profile before the duration and interval; the latter
fields are not available until the former is set to 'rolling'.
* the 'Closed library due date management' field is now required
so we provide a setting, 'keep the current due date/time'.
(choosing one of the 'move' options generates the following
okapi error during checkout:
````
{
"errors" : [ {
"message" : "Calendar timetable is absent for requested date",
"parameters" : [ ]
} ]
}
````
* do a better job determining if a checkout is successful
Even with these changes in place, note that this test *still fails*
due to trouble with renewal, but there are fewer overall failures.
Refs [UICIRC-237](https://issues.folio.org/browse/UICIRC-237)
> loan-renewal test tweaks

- test/ui-testing/new-request.js
The same user cannot have an item checked out and create a request for
it. Now that this requirement is being respected on the backend, we must
respect it on the front as well.
Refs [UICIRC-237](https://issues.folio.org/browse/UICIRC-237)
> use distinct check out/request users

- test/ui-testing/loan-renewal.js
Don't wait for edit-button when confirming delete. After the delete is
processed, no loan-item will be selected, hence no edit-button will be
available. The `.wait('#clickable-edit-item')` line was left over from a
previous incarnation of the tests. It didn't cause trouble in other test
environments where the test must breeze past it while still showing the
policy's details, but for some reason it doesn't work that way in CI.
Refs [UICIRC-237](https://issues.folio.org/browse/UICIRC-237)
> better delete/wait handling

- test/ui-testing/loan-renewal.js
I don't know how/why this wait clause was added in the last PR, but it
was not intentional and it breaks the tests so now I'm getting rid of
it.
> remove extraneous wait clause

- test/ui-testing/exercise.js
- test/ui-testing/loan-renewal.js
- test/ui-testing/new-proxy.js
- test/ui-testing/new-request.js
- test/ui-testing/profile-pictures.js
The active/inactive checkboxes were restored in folio-org/ui-users/pull/811
which means we need to check the 'active' checkbox when looking for
users, otherwise we'll get inactive users in the mix who don't have the
ability to, e.g., check out an item or place a request.
Refs [UITEST-64](https://issues.folio.org/browse/UITEST-64)
> choose active users only

- test/ui-testing/new-request.js
Oy selecting users when multiple filters are in place is a mess. The
original "wait for the count to be non-zero" selector no longer works
because the count becomes non-zero after the first filter is applied.
This means checking for a non-zero count after the second filter can
return true, allowing flow to move on while the list is still changing
because the second filter hasn't yet been applied.
This can result in selecting diku_admin, which has no barcode, or an
inactive user, who is not allowed to perform a checkout.
> better user selection

- test/ui-testing/new-proxy.js
ui-plugin-find-user does not wrap search result rows in `a` tags the way
ui-users does, and since the plugin no longer relies on ui-users under
the hood, the selector needs to be updated accordingly.
> fix proxy tests

- CHANGELOG.md
- package.json
- stripes.config.js
Eventually, tenant-settings will replace organization. The first step is
to add tenant-settings.
Refs [UIORG-156](https://issues.folio.org/browse/UIORG-156)
> add tenant-settings to replace organization

- test/ui-testing/loan-renewal.js
Oh, the irony: nav elements in `<EntrySelector>` got a new div-wrapper
in folio-org/stripes-smart-components/pull/494 so we
could include a `data-test-foo` element to write better unit tests. But
that extra markup broke the integration tests. You can't win!
> accommodate new EntrySelector markup

- test/ui-testing/new-proxy.js
- test/ui-testing/new-request.js
`helpers.openApp` uses the nav-bar to navigate between apps but we need
to use the app-menu in case the requested app has been pushed off the
bar.
Refs [UITEST-65](https://issues.folio.org/browse/UITEST-65)
> purge openApp

- test/ui-testing/loan-renewal.js
modals interact badly with Nightmare tests. If a test ends while a modal
is still visible, Nightmare seems to get lost in neverneverland and
cannot start the next test.
> wait until modals expire

- test/ui-testing/loan-renewal.js
- test/ui-testing/new-request.js
Correctly use the setCirculationRules helper to get and restore
circulation rules reliably.
Refs [UITEST-67](https://issues.folio.org/browse/UITEST-67)
> UITEST-67 correctly handle circulation rules

- test/ui-testing/codex-search.js
Prior to folio-org/stripes-smart-components/pull/583 checkbox IDs were
based on raw values which could contain spaces and other characters that
are illegal for HTML element IDs. Now those values are converted to
kebab-case first, and the tests must reflect that.
> checkbox IDs use kebab-case

- test/ui-testing/loan-renewal.js
- test/ui-testing/new-request.js
`stripes-testing`'s `setCirculationRules` function now returns a
promise. In order to capture the value in that promise in a variable in
the test, that promise needs to be resolved via a `then` block.
Refs [FOLIO-2192](https://issues.folio.org/browse/FOLIO-2192)
> FOLIO-2192 correctly use setCirculationRules

- package.json
stripes and the platform both have a hard dep on react but not with the
same restriction; the platform uses `^` and stripes  `~`. Probably we
only want a hard dep in one place. Until that's resolved, we need to at
least use a consistent dependency so we don't get multiple versions of
React in the build when different versions satisfy the different
dependencies (as when 16.9 was released, which is permitted by ^16.8 but
not by ~16.8).
Refs [UIIN-678](https://issues.folio.org/browse/UIIN-678)
> use more conservative ~ dep on react

- install.json
- okapi-install.json
- package.json
- stripes-install.json
- test/ui-testing/codex-search.js
- test/ui-testing/new-request.js
- yarn.lock
Update #master to stripes `v2.10.1` and ui-users `v2.25.1`. This stripes-components update changes the structure of the MCL component and integration tests that rely on this component are distributed across many modules, including ui-users and platform-core, hence merging the platform's test updates simultaneously with the stripes-components and ui-users updates. 
* react 16.8
We have many modules that make use of hooks, so we need a react
instance that provides hooks
* @folio/stripes 2.10.1
Introduce many change to the `<MultiColumnList>` component which 
must be reflected in integration test updates across multiple repositories,
including ui-users and platform-core.
* @folio/checkin 1.9
Update the react-to-print version to accept React via peerDependencies
in order to avoid bundling and …
> Merge monster

- test/ui-testing/new-proxy.js
Nightmare appears to be getting hung up in some MCL selections. I'm not
sure how this is coming up now given that this passed for several days,
but here we are. Removing some of the markup and leaving the selector to
stand on semantic markup alone seems to do the trick.
Refs [UITEST-70](https://issues.folio.org/browse/UITEST-70)
> UITEST-70 be less markupy, more semantic

- package.json
- yarn.lock
`react-router` and `react-router-dom` need to be provided by the platform as
dependencies for the platform's constituent modules to consume as
peerDependencies in order to guarantee that all modules are on the same
version. Modules may pass `<Link>` instances across module borders so we
need to be certain all modules agree on the same version of `<Link>` in
order to avoid crashing React.
Refs [STCOM-581](https://issues.folio.org/browse/STCOM-581)
> STCOM-581 provide react-router as a peerDep

- package.json
Reverts folio-org/platform-core#406
When individual apps still include react-router v4, this causes an error:
```
ERROR:Invariant failed: You should not use <Switch> outside a <Router>
```
> Revert "STCOM-581 provide react-router as a peerDep"

- package.json
- test/ui-testing/new-proxy.js
- test/ui-testing/new-request.js
- test/ui-testing/profile-pictures.js
- test/ui-testing/stub.js
- test/ui-testing/vendor.js
- yarn.lock
- Fulfills part of https://issues.folio.org/browse/STRIPES-648.
- Updated `eslint-config-stripes` to 5.0.0 which also contains updated version of `eslint`.
- Removed `global` comments as v6 has more strict `no-redeclare` rules: https://eslint.org/docs/user-guide/migrating-to-6.0.0#no-redeclare-updates.
> Security update eslint to >= 6.2.1 or eslint-util >= 1.4.1

- package.json
- test/ui-testing/new-proxy.js
- test/ui-testing/new-request.js
- test/ui-testing/profile-pictures.js
- test/ui-testing/stub.js
- test/ui-testing/vendor.js
- yarn.lock
- Fulfills part of https://issues.folio.org/browse/STRIPES-648.
- Updated eslint-config-stripes to 5.0.0 which also contains updated version of eslint.
- Removed global comments as v6 has more strict no-redeclare rules: https://eslint.org/docs/user-guide/migrating-to-6.0.0#no-redeclare-updates.
> Snapshot stripes 648

- test/ui-testing/exercise.js
- test/ui-testing/loan-renewal.js
- test/ui-testing/new-request.js
Circulation rule syntax is not technically part of the API surface, so
this new requirement to have an overdue policy with every rule snuck in
without anybody on the UI side noticing.
These changes provide a dummy policy, `o test-overdue`, in the rules but
do not actually handle creating and removing such a policy in the UI.
We should add that.
Refs [CIRC-495](https://issues.folio.org/browse/CIRC-495)
> CIRC-495 overdue policy is required

- test/ui-testing/loan-renewal.js
The submit and cancel buttons moved to a fixed-footer in
folio-org/ui-circulation/pull/456. This syncs the integration test with
that change.
Refs [UICIRC-367](https://issues.folio.org/browse/UICIRC-367)
> UICIRC-367 update save-entity button IDs

- package.json
Recent updates in final-form (v4.18.6) and react-final-form (v6.3.1)
caused a lot of grief for us. From what I can tell, the handling of
`initialValues` changed dramatically. This PR locks those libraries
at v4.18.5 and v6.3.0, respectively.
Our initial patch for UIIN-875 involved provided an empty object where
none was previously required. That solved one problem but created
another: because the form now always receives an empty object on its
first render, its props always change on subsequent renders when
editing existing objects and this happens to cause problems with the
barcode-validator.
There, an optimization makes an API call only if the current value is
different than the initial value. Because that initial value is now
always defined (and always empty), the API call happens when …
> UIIN-875 UIIN-878 lock final-form libraries

- test/ui-testing/loan-renewal.js
A backend change now requires including a "lost item" policy reference
in every rule. Who knew? I LOVE it that we don't have a way to version
circ-rule syntax changes in our API. It's totally my favorite thing.
`</sarcasm>`. OK, I get why it doesn't work that way because the API
endpoint just accepts a text-string not a JSON object, but that still
sucks.
All I want for Christmas is an API that accepts circulation rules as
JSON instead of as a string. Or a hippopotamus. A hippopotamus is no
ignormaus and would sing me this sweet serenade:
JSON, JSON, glorious JSON
Nothing quite like for spec'ing the types in
Ugh. POST with me, POST
A string to the host
Until we can send it some glorious JSON.
Alas, I fear somebody is about to punch out my two front teeth and leave
me instead a big old box …
> add lost-item policy to circ rules

- test/ui-testing/loan-renewal.js
- test/ui-testing/many-items.js
- test/ui-testing/new-proxy.js
- test/ui-testing/new-request.js
This is a follow-up to #524, applying the same changes to additional
tests.
Use helpers to add/remove overdue fine policy, lost item fee policy, and
patron notice policy in the circulation rules that are created. Checkout
is now smart enough to check all the attributes of circulation policies
and if we just use dummy values, checkout will fail.
> FOLIO-2440 create temporary policies

- test/ui-testing/loan-renewal.js
The loan-renewal test had an extra describe wrapper around the
restore-settings section. No longer.
> FOLIO-2440 remove extra describe wrapper

- test/ui-testing/new-request.js
Circulation rules must be saved _after_ configuring the policies that
will be used in them. Related, that function also must be wrapped in a
`describe` block _and_ moved below the policy config. `it` blocks are
executed before `describe` blocks.
> FOLIO-2440 circ rules need a describe block

- package.json
We could have unlocked these resolutions months ago when
@aditya-matukumalli debugged this as a problem with `initialValues` and
merged folio-org/stripes-final-form/pull/19.
Refs [STRIPES-664](https://issues.folio.org/browse/STRIPES-664)
> STRIPES-664 unlock final-form resolution

- install.json
- package.json
- stripes-install.json
- test/ui-testing/new-request.js
- yarn.lock
[`ui-requests` `v1.14.4`](https://github.com/folio-org/ui-requests/releases/v1.14.4) moves the save/cancel buttons to the form-footer and changes the HTML
`id` attribute.
Refs [UIREQ-370](https://issues.folio.org/browse/UIREQ-370)
> UIREQ-370 update ui-requests and its tests

- package.json
Update `@folio/stripes` to `^3.0.0`. In addition, update React and
include `react-router` and `react-intl` as direct dependencies so that
other apps may include them as peers.
> update stripes to v3.0.0

- package.json
- test/ui-testing/many-items.js
`stripes-testing` `v2.0.0`, available in `stripes-cli` `v1.15.0`,
correctly waits for all checkout actions to complete, rather than
immediately calling `done`, and returns the promise to the test to
allow `done` to be called there.
> better checkout-list handling

- test/ui-testing/exercise.js
The tests looking for a changed open loan count, or for the
checked-out item in open loans started failing recently when running
locally. It is not at all clear why, but pausing here and there seems to
make nightmare happier.
> tweak exercise test

- test/ui-testing/loan-renewal.js
Circulation-related settings used to have a selector like `a div` but it
appears that switched to `div a` ... somewhere, probably in
`<MultiColumnList>` in stripes-components. This update tries to make the
selectors a little bit more semantic/robust. I'm not sure if it actually
does that or if it just rearranges things, but in any case tests work
again, so, yay.
See also folio-org/stripes-testing/pull/69 for parallel changes in the
shared handlers.
> update MCL anchor handling (#69)

- package.json
Pin `moment` at `~2.24.0` in light of multiple issues with `2.25.0` ([5489](https://github.com/moment/moment/issues/5489), [5472](https://github.com/moment/moment/issues/5472)).
Refs [STRIPES-678](https://issues.folio.org/browse/STRIPES-678)
> STRIPES-678 resolve moment to v2.24.0

- package.json
Provide a direct dep on `moment` `~2.24.0` so other repositories may
depend on it as a peer. Because we configure moment with the current
locale, it is important that all modules receive that same instance.
Refs [STRIPES-635](https://issues.folio.org/browse/STRIPES-635), [STRIPES-678](https://issues.folio.org/browse/STRIPES-678)
> STRIPES-635 -678 provide moment v2.24 to peers

- test/ui-testing/codex-search.js
`evaluate()` only runs once but `wait()` runs until its condition
returns true. This last test started failing out of the blue a few days
ago for no clear reason -- no changes in ui-search -- but perhaps
something deeper down in the render hierarchy is causing it to go
through an extra cycle that we need to accommodate here.
> wait, not evaluate, for search results

- test/ui-testing/loan-renewal.js
The `Edit` button for loan policies moved from a button into a dropdown
menu as part of UICIRC-437 /
/folio-org/stripes-smart-components/pull/806.
Refs [UICIRC-437](https://issues.folio.org/browse/UICIRC-437)
> CIRC-437 test updates

- CHANGELOG.md
- package.json
Move `react-intl` from `^4.5` to `~4.6` to avoid the broken `4.7` series,
https://github.com/formatjs/formatjs/issues/1744.
> avoid buggy react-intl v4.7

- package.json
because of prototype pollution security issue. See here for more info: https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764
> Ensure minimist is at least v1.2.3 in dependencies

- test/ui-testing/loan-renewal.js
The request policy form was [recently refactored](https://github.com/folio-org/ui-circulation/pull/535) to use final-form, and Nightmare is super unhappy about that. It isn't entirely clear what the issue is. We [discussed this on Slack](https://folio-project.slack.com/archives/C210UCHQ9/p1593176052423400) but didn't reach any firm conclusions.
The approach here is to simply avoid interacting with the request policy
form since we don't actually do anything request-policy-related in the
tests.
> use default request-policy

- CHANGELOG.md
- package.json
- stripes.config.js
This PR includes https://github.com/folio-org/ui-plugin-create-inventory-records to the list of dependencies.
> Add create-inventory-records plugin

- package.json
I love this test. It is my favorite test in all off my nightmare tests.
I love this test the most because it always succeeds when I run it in
isolation and always fails when I run it as part of the suite. This
makes it extra special and extra deserving of my love. NightmareJS and
consistent test results walk hand in hand together like love, marriage,
and ritual infanticide. A test is a test of course, I Jest, and no one
can talk to a test unless, that is, oh hell, unless you spell, your test
like R-T-L. What if the BigTest is not big enough? _He cries_. Writing
more tests in NightmareJS will liquify the nerves of the sentient beings
*it begins*. It is a journey. It is a journey up a river of c͒ͪo͛ͫrruption.
*_He comes_*. It is a journey across the water in search of a m̡adman,
in se̶arch …
> FOLIO-2727 temporarily disable flakey tests

- CHANGELOG.md
- package.json
Increment `redux` to `v4`, `react-redux` to `v7`.
Refs [STRIPES-721](https://issues.folio.org/browse/STRIPES-721)
> STRIPES-721 upgrade to react-redux 7

- package.json
redux-form probably needs to be a peer-dep so that things like
stripes-components and ui-apps all have the same expectations about the
underlying redux store.
Refs [STCOR-504](https://issues.folio.org/browse/STCOR-504)
> STCOR-504 force redux-form v8 on apps

- CHANGELOG.md
- package.json
Pin `@folio/stripes-cli` to `v2` via resolutions so we don't get
multiple copies of `@folio/stripes-core` and `@folio/stripes-components`
via `v1`. We can remove the resolutions entry as soon as all the tickets
linked to [STCLI-169](https://issues.folio.org/browse/STCLI-169) are closed.
Refs [STRIPES-733](https://issues.folio.org/browse/STRIPES-733)
> STRIPES-733 update stripes-cli to v2

- CHANGELOG.md
- package.json
`stripes-core` wraps apps in contexts for `react-query` and `swr`, so we
need to provide those modules at the platform level so all modules can
depend on the same version as peers.
Refs [STRIPES-735](https://issues.folio.org/browse/STRIPES-735)
> STRIPES-735 provide react-query, swr

- package.json
- yarn.lock
- Fulfills [STRIPES-726](https://issues.folio.org/browse/STRIPES-726).
- Prevents all packages from running scripts when installing.
- The one script needed is `stripes-core` building icons which is allowed by adding `npm rebuild sharp` as a `postinstall` step which automatically runs after `install`.
> Ignore scripts and add postinstall step to build icons
